/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agents Stream */
        post: operations["agents_stream_api_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agents Schema Endpoint */
        get: operations["agents_schema_endpoint_api_agents_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Benchmarks Endpoint */
        get: operations["benchmarks_endpoint_api_benchmarks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_api_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Config Endpoint */
        get: operations["read_config_endpoint_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Config Endpoint */
        patch: operations["patch_config_endpoint_api_config_patch"];
        trace?: never;
    };
    "/api/config/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Config Test Endpoint */
        post: operations["config_test_endpoint_api_config_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cron */
        get: operations["list_cron_api_cron_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Cron */
        delete: operations["delete_cron_api_cron__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron/{job_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Cron */
        post: operations["disable_cron_api_cron__job_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cron/{job_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable Cron */
        post: operations["enable_cron_api_cron__job_id__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Doctor Endpoint */
        get: operations["doctor_endpoint_api_doctor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/exec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fs Exec Stream */
        post: operations["fs_exec_stream_api_fs_exec_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fs File Endpoint */
        get: operations["fs_file_endpoint_api_fs_file_get"];
        /** Fs File Write Endpoint */
        put: operations["fs_file_write_endpoint_api_fs_file_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fs Tree Endpoint */
        get: operations["fs_tree_endpoint_api_fs_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/git/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Git Commit Endpoint */
        post: operations["git_commit_endpoint_api_git_commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/git/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Git Diff Endpoint */
        get: operations["git_diff_endpoint_api_git_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/git/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Git Revert Endpoint */
        post: operations["git_revert_endpoint_api_git_revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/git/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Git Status Endpoint */
        get: operations["git_status_endpoint_api_git_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/governance/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Governance Audit Endpoint */
        get: operations["governance_audit_endpoint_api_governance_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/governance/injection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Governance Injection Endpoint */
        get: operations["governance_injection_endpoint_api_governance_injection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/kanban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Kanban */
        get: operations["get_kanban_api_kanban_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maturity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Maturity Endpoint */
        get: operations["maturity_endpoint_api_maturity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mcp List Endpoint */
        get: operations["mcp_list_endpoint_api_mcp_get"];
        put?: never;
        /** Mcp Add Endpoint */
        post: operations["mcp_add_endpoint_api_mcp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Mcp Remove Endpoint */
        delete: operations["mcp_remove_endpoint_api_mcp__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/{name}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mcp Test Endpoint */
        post: operations["mcp_test_endpoint_api_mcp__name__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memory */
        get: operations["list_memory_api_memory_get"];
        put?: never;
        /** Add Memory */
        post: operations["add_memory_api_memory_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory Layers */
        get: operations["memory_layers_api_memory_layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory Profile */
        get: operations["memory_profile_api_memory_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Memory */
        delete: operations["delete_memory_api_memory__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan Endpoint */
        post: operations["plan_endpoint_api_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Project */
        post: operations["approve_project_api_projects__project_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/deny": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deny Project */
        post: operations["deny_project_api_projects__project_id__deny_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs Endpoint */
        get: operations["runs_endpoint_api_runs_get"];
        put?: never;
        /** Run Stream */
        post: operations["run_stream_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        /** New Session */
        post: operations["new_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_api_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Skill */
        post: operations["approve_skill_api_skills__name__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{name}/retire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retire Skill */
        post: operations["retire_skill_api_skills__name__retire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tools Endpoint */
        get: operations["tools_endpoint_api_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usage Endpoint */
        get: operations["usage_endpoint_api_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentResultOut */
        AgentResultOut: {
            /** Attempts */
            attempts: number;
            /** Changed Paths */
            changed_paths: string[];
            /** Diffs */
            diffs: components["schemas"]["FileDiffOut"][];
            /** Index */
            index: number;
            /** Reverted */
            reverted: boolean;
            /** Success */
            success: boolean;
            /** Task */
            task: string;
        };
        /** AgentTaskIn */
        AgentTaskIn: {
            /** Task */
            task: string;
            /** Verify */
            verify?: string | null;
        };
        /** AgentsBatchOut */
        AgentsBatchOut: {
            /** Conflicts */
            conflicts: string[];
            /** Is Repo */
            is_repo: boolean;
            /** Merged */
            merged: number;
            /** Results */
            results: components["schemas"]["AgentResultOut"][];
        };
        /**
         * AgentsRequest
         * @description A batch of coding tasks for the Agent Manager: each runs concurrently in its OWN git worktree.
         *
         *     Mirrors ``chimera solve-batch``. Isolation is REAL only in a git repo — outside one the tasks run
         *     in-place against ``workspace`` with no isolation (so concurrent edits can collide and conflicts
         *     can't be detected); the response's ``is_repo`` flag says which happened, honestly.
         */
        AgentsRequest: {
            /**
             * Cascade
             * @default false
             */
            cascade: boolean;
            /**
             * Fuse
             * @default false
             */
            fuse: boolean;
            /**
             * Max Workers
             * @default 4
             */
            max_workers: number;
            /** Model */
            model?: string | null;
            /** Tasks */
            tasks: components["schemas"]["AgentTaskIn"][];
            /** Workspace */
            workspace?: string | null;
        };
        /** ApproveBody */
        ApproveBody: {
            /** Card */
            card?: string | null;
        };
        /** ApprovedOut */
        ApprovedOut: {
            /** Approved */
            approved: boolean;
        };
        /** AttemptReceiptOut */
        AttemptReceiptOut: {
            /** Diff Summary */
            diff_summary: string;
            /** Diffs */
            diffs: components["schemas"]["FileDiffOut"][];
            /** Feedback */
            feedback: string;
            /** Index */
            index: number;
            /** Reverted */
            reverted: boolean;
            /** Success */
            success: boolean;
            /** Verified */
            verified: boolean;
            /** Verify Output */
            verify_output: string;
        };
        /** AuditEventOut */
        AuditEventOut: {
            /** Seq */
            seq: number;
            /** Summary */
            summary: string;
            /** Type */
            type: string;
        };
        /** BenchmarkExternalOut */
        BenchmarkExternalOut: {
            /** Baseline Rate */
            baseline_rate: number;
            /** Benchmark */
            benchmark: string;
            /** Ci */
            ci: number[];
            /** Delta */
            delta: number;
            /** Model */
            model: string;
            /** N */
            n: number;
            /** Note */
            note: string;
            /** Significant */
            significant: boolean;
            /** Source */
            source: string;
            /** Treatment Rate */
            treatment_rate: number;
        };
        /** BenchmarkLiftOut */
        BenchmarkLiftOut: {
            /** Baseline Rate */
            baseline_rate: number;
            /** Ci */
            ci: number[];
            /** Delta */
            delta: number;
            /** Model */
            model: string;
            /** N */
            n: number;
            /** Note */
            note: string;
            /** Significant */
            significant: boolean;
            /** Source */
            source: string;
            /** Suite */
            suite: string;
            /** Treatment Rate */
            treatment_rate: number;
        };
        /** BenchmarksOut */
        BenchmarksOut: {
            /** Available */
            available: boolean;
            /** External */
            external: components["schemas"]["BenchmarkExternalOut"][];
            /** Generated For */
            generated_for: string | null;
            internal_lift: components["schemas"]["BenchmarkLiftOut"] | null;
        };
        /** CacheCfgOut */
        CacheCfgOut: {
            /** Completion */
            completion: boolean;
            /** Prompt */
            prompt: boolean;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Fuse
             * @default false
             */
            fuse: boolean;
            /** Message */
            message: string;
            /** Session Id */
            session_id?: string | null;
            /**
             * Stream
             * @default true
             */
            stream: boolean;
        };
        /** ConfigOut */
        ConfigOut: {
            cache: components["schemas"]["CacheCfgOut"];
            mcp: components["schemas"]["McpCfgOut"];
            memory: components["schemas"]["MemoryCfgOut"];
            models: components["schemas"]["ModelsCfgOut"];
            /** Providers */
            providers: components["schemas"]["ProviderOut"][];
            sandbox: components["schemas"]["SandboxCfgOut"];
            server: components["schemas"]["ServerCfgOut"];
        };
        /** ConfigTestOut */
        ConfigTestOut: {
            /** Error */
            error: string | null;
            /** Model */
            model: string;
            /** Ok */
            ok: boolean;
        };
        /** ConfigTestRequest */
        ConfigTestRequest: {
            /** Model */
            model?: string | null;
        };
        /** CronJobOut */
        CronJobOut: {
            /** Action */
            action: string;
            /** Created By */
            created_by: string;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: string;
            /** Last Run */
            last_run: number | null;
            /** Name */
            name: string;
            /** Next Run */
            next_run: number | null;
            /** Schedule */
            schedule: string;
            /** Trigger */
            trigger: string;
        };
        /** DeletedOut */
        DeletedOut: {
            /** Deleted */
            deleted: boolean;
        };
        /** DoctorOut */
        DoctorOut: {
            /** Cache */
            cache: boolean;
            /** Configured Providers */
            configured_providers: string[];
            /** Default Model */
            default_model: string;
            /** Has Any Key */
            has_any_key: boolean;
            /** Memory Backend */
            memory_backend: string;
            /** Sandbox */
            sandbox: string;
            tiers: components["schemas"]["TiersOut"];
        };
        /** ExecRequest */
        ExecRequest: {
            /** Command */
            command: string;
            /**
             * Cwd
             * @default
             */
            cwd: string;
            /**
             * Timeout
             * @default 60
             */
            timeout: number;
            /** Workspace */
            workspace?: string | null;
        };
        /** FileDiffOut */
        FileDiffOut: {
            /** Patch */
            patch: string;
            /** Path */
            path: string;
            /** Truncated */
            truncated: boolean;
        };
        /** FsFileOut */
        FsFileOut: {
            /** Content */
            content: string;
            /** Note */
            note: string;
            /** Path */
            path: string;
            /** Truncated */
            truncated: boolean;
        };
        /** FsFileWriteRequest */
        FsFileWriteRequest: {
            /** Content */
            content: string;
            /** Path */
            path: string;
            /** Workspace */
            workspace?: string | null;
        };
        /** FsFileWrittenOut */
        FsFileWrittenOut: {
            /** Bytes */
            bytes: number;
            /** Path */
            path: string;
        };
        /** FsNodeOut */
        FsNodeOut: {
            /** Is Dir */
            is_dir: boolean;
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /** FsTreeOut */
        FsTreeOut: {
            /** Capped */
            capped: boolean;
            /** Entries */
            entries: components["schemas"]["FsNodeOut"][];
            /** Path */
            path: string;
            /** Workspace */
            workspace: string;
        };
        /** GitCommitOut */
        GitCommitOut: {
            /** Commit */
            commit: string;
            /** Error */
            error: string | null;
            /** Ok */
            ok: boolean;
            /** Output */
            output: string;
        };
        /** GitCommitRequest */
        GitCommitRequest: {
            /** Message */
            message: string;
            /** Paths */
            paths: string[];
            /** Workspace */
            workspace?: string | null;
        };
        /** GitDiffOut */
        GitDiffOut: {
            /** Is Repo */
            is_repo: boolean;
            /** Patch */
            patch: string;
        };
        /** GitFileOut */
        GitFileOut: {
            /** Path */
            path: string;
            /** Staged */
            staged: boolean;
            /** Untracked */
            untracked: boolean;
            /** X */
            x: string;
            /** Y */
            y: string;
        };
        /** GitRevertOut */
        GitRevertOut: {
            /** Error */
            error: string | null;
            /** Ok */
            ok: boolean;
            /** Reverted */
            reverted: string[];
        };
        /** GitRevertRequest */
        GitRevertRequest: {
            /** Paths */
            paths: string[];
            /** Workspace */
            workspace?: string | null;
        };
        /** GitStatusOut */
        GitStatusOut: {
            /** Branch */
            branch: string;
            /** Files */
            files: components["schemas"]["GitFileOut"][];
            /** Is Repo */
            is_repo: boolean;
        };
        /** GovernanceAuditOut */
        GovernanceAuditOut: {
            /** Count */
            count: number;
            /** Events */
            events: components["schemas"]["AuditEventOut"][];
            /** Populated */
            populated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Sessions */
            sessions: number;
            /** Status */
            status: string;
        };
        /** InjectionAttackOut */
        InjectionAttackOut: {
            /** Blocked Defended */
            blocked_defended: boolean;
            /** Blocked Undefended */
            blocked_undefended: boolean;
            /** Category */
            category: string;
            /** Harmful Tool */
            harmful_tool: string;
            /** Id */
            id: string;
        };
        /** InjectionCategoryOut */
        InjectionCategoryOut: {
            /** Category */
            category: string;
            /** Count */
            count: number;
            /** Defended Asr */
            defended_asr: number;
            /** Undefended Asr */
            undefended_asr: number;
        };
        /** InjectionReportOut */
        InjectionReportOut: {
            /** Attacks */
            attacks: components["schemas"]["InjectionAttackOut"][];
            /** By Category */
            by_category: components["schemas"]["InjectionCategoryOut"][];
            /** Defended Asr */
            defended_asr: number;
            /** Defended Block Rate */
            defended_block_rate: number;
            /** Leaks Defended */
            leaks_defended: string[];
            /** Total Attacks */
            total_attacks: number;
            /** Undefended Asr */
            undefended_asr: number;
            /** Undefended Block Rate */
            undefended_block_rate: number;
        };
        /** MaturityOut */
        MaturityOut: {
            /** Available */
            available: boolean;
            /** Generated For */
            generated_for: string | null;
            /** Level */
            level: string;
            /** Proven */
            proven: number;
            /** Ratio */
            ratio: number;
            /** Source */
            source: string | null;
            /** Surfaces */
            surfaces: components["schemas"]["MaturitySurfaceOut"][];
            /** Total */
            total: number;
            weakest: components["schemas"]["MaturityWeakestOut"] | null;
        };
        /** MaturitySurfaceOut */
        MaturitySurfaceOut: {
            /** Level */
            level: string;
            /** Missing */
            missing: string[];
            /** Name */
            name: string;
            /** Proven */
            proven: number;
            /** Ratio */
            ratio: number;
            /** Total */
            total: number;
        };
        /** MaturityWeakestOut */
        MaturityWeakestOut: {
            /** Name */
            name: string;
            /** Ratio */
            ratio: number;
        };
        /** McpAddRequest */
        McpAddRequest: {
            /**
             * Args
             * @default []
             */
            args: string[];
            /** Command */
            command: string;
            /**
             * Env
             * @default {}
             */
            env: {
                [key: string]: string;
            };
            /** Name */
            name: string;
        };
        /** McpCfgOut */
        McpCfgOut: {
            /** Autoload */
            autoload: boolean;
        };
        /** McpServerOut */
        McpServerOut: {
            /** Args */
            args: string[];
            /** Command */
            command: string;
            /** Env Keys */
            env_keys: string[];
            /** Name */
            name: string;
        };
        /** McpServersOut */
        McpServersOut: {
            /** Count */
            count: number;
            /** Servers */
            servers: components["schemas"]["McpServerOut"][];
        };
        /** McpTestOut */
        McpTestOut: {
            /** Error */
            error: string | null;
            /** Ok */
            ok: boolean;
            /** Tools */
            tools: components["schemas"]["McpToolOut"][];
        };
        /** McpToolOut */
        McpToolOut: {
            /** Description */
            description: string;
            /** Name */
            name: string;
        };
        /** MemoryAdd */
        MemoryAdd: {
            /** Content */
            content: string;
            /** Key */
            key?: string | null;
            /**
             * Kind
             * @default semantic
             */
            kind: string;
        };
        /** MemoryAddOut */
        MemoryAddOut: {
            item: components["schemas"]["MemoryItemOut"];
            /** Status */
            status: string;
        };
        /** MemoryCfgOut */
        MemoryCfgOut: {
            /** Auto Consolidate */
            auto_consolidate: boolean;
            /** Backend */
            backend: string;
            /** Semantic */
            semantic: boolean;
        };
        /** MemoryItemOut */
        MemoryItemOut: {
            /** Content */
            content: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Provenance */
            provenance: string;
            /** Source */
            source: string;
        };
        /** MemoryLayerOut */
        MemoryLayerOut: {
            /** Clean */
            clean: number;
            /** Count */
            count: number;
            /** Kind */
            kind: string;
            /** Tainted */
            tainted: number;
        };
        /** MemoryLayersOut */
        MemoryLayersOut: {
            /** By Source */
            by_source: components["schemas"]["MemorySourceOut"][];
            /** Clean */
            clean: number;
            /** Layers */
            layers: components["schemas"]["MemoryLayerOut"][];
            /** Semantic Embeddings Enabled */
            semantic_embeddings_enabled: boolean;
            /** Tainted */
            tainted: number;
            /** Total */
            total: number;
        };
        /** MemoryProfileOut */
        MemoryProfileOut: {
            /** Persona */
            persona: components["schemas"]["MemoryItemOut"][];
            /** Profile */
            profile: string;
        };
        /** MemorySourceOut */
        MemorySourceOut: {
            /** Count */
            count: number;
            /** Source */
            source: string;
        };
        /** ModelsCfgOut */
        ModelsCfgOut: {
            /** Api Base */
            api_base: string | null;
            /** Cascade */
            cascade: boolean;
            /** Cost Mode */
            cost_mode: string;
            /** Default */
            default: string;
            /** Fallback Models */
            fallback_models: string[];
            /** Mid */
            mid: string;
            /** Orchestrator */
            orchestrator: string;
            tiers: components["schemas"]["TiersOut"];
            /** Weak */
            weak: string;
        };
        /** NewSessionOut */
        NewSessionOut: {
            /** Id */
            id: string;
        };
        /** PlanOut */
        PlanOut: {
            /** Note */
            note: string;
            /** Steps */
            steps: string[];
            /** Text */
            text: string;
        };
        /** PlanRequest */
        PlanRequest: {
            /** Task */
            task: string;
            /** Workspace */
            workspace?: string | null;
        };
        /** ProjectDetailOut */
        ProjectDetailOut: {
            /** Columns */
            columns: {
                [key: string]: components["schemas"]["TaskCardOut"][];
            };
            state: components["schemas"]["ProjectStateOut"];
        };
        /** ProjectStateOut */
        ProjectStateOut: {
            /** Id */
            id: string;
            /** Iterations */
            iterations: number;
            /** Max Iterations */
            max_iterations: number;
            /** Note */
            note: string;
            /** Pending Card Id */
            pending_card_id: string | null;
            /** Plan Approved */
            plan_approved: boolean;
            /** Status */
            status: string;
        };
        /** ProviderOut */
        ProviderOut: {
            /** Env */
            env: string;
            /** Hint */
            hint: string;
            /** Label */
            label: string;
            /** Set */
            set: boolean;
        };
        /** RetiredOut */
        RetiredOut: {
            /** Retired */
            retired: boolean;
        };
        /** RunReceiptOut */
        RunReceiptOut: {
            /** Answer */
            answer: string;
            /** Attempts */
            attempts: components["schemas"]["AttemptReceiptOut"][];
            /** Paused */
            paused: boolean;
            /** Success */
            success: boolean;
            /** Task */
            task: string;
            /** Ts */
            ts: string;
            /** Verify Command */
            verify_command: string | null;
        };
        /** RunRequest */
        RunRequest: {
            /**
             * Cascade
             * @default false
             */
            cascade: boolean;
            /**
             * Fuse
             * @default false
             */
            fuse: boolean;
            /**
             * Max Attempts
             * @default 3
             */
            max_attempts: number;
            /** Model */
            model?: string | null;
            /** Plan */
            plan?: string | null;
            /** Task */
            task: string;
            /** Verify */
            verify?: string | null;
            /** Workspace */
            workspace?: string | null;
        };
        /** SandboxCfgOut */
        SandboxCfgOut: {
            /** Image */
            image: string;
            /** Mode */
            mode: string;
        };
        /** ServerCfgOut */
        ServerCfgOut: {
            /** Token Set */
            token_set: boolean;
        };
        /** SessionDetailOut */
        SessionDetailOut: {
            /** Id */
            id: string;
            /** Turns */
            turns: components["schemas"]["TurnOut"][];
        };
        /** SessionMetaOut */
        SessionMetaOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Turns */
            turns: number;
            /** Updated At */
            updated_at: number;
        };
        /** SkillStatOut */
        SkillStatOut: {
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Provenance */
            provenance: string;
            /** Rate */
            rate: number | null;
            /** Status */
            status: string;
            /** Successes */
            successes: number;
            /** Uses */
            uses: number;
        };
        /** SkillsOut */
        SkillsOut: {
            /** Retirement Candidates */
            retirement_candidates: string[];
            /** Stats */
            stats: components["schemas"]["SkillStatOut"][];
        };
        /** TaskCardOut */
        TaskCardOut: {
            /** Action */
            action: string;
            /** Column */
            column: string;
            /** Depends On */
            depends_on: string[];
            /** Id */
            id: string;
            /** Risk */
            risk: string | null;
            /** Success */
            success: boolean | null;
            /** Title */
            title: string;
        };
        /** TiersOut */
        TiersOut: {
            /** Mid */
            mid: string;
            /** Top */
            top: string;
            /** Weak */
            weak: string;
        };
        /** ToolInfoOut */
        ToolInfoOut: {
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Params */
            params: string[];
            /** Tags */
            tags: string[];
            /** Untrusted Output */
            untrusted_output: boolean;
        };
        /** ToolsOut */
        ToolsOut: {
            /** Count */
            count: number;
            /** Tools */
            tools: components["schemas"]["ToolInfoOut"][];
        };
        /** TurnOut */
        TurnOut: {
            /** Assistant */
            assistant: string;
            /** User */
            user: string;
        };
        /** UpdatedOut */
        UpdatedOut: {
            /** Updated */
            updated: string[];
        };
        /** UsageDayOut */
        UsageDayOut: {
            /** Completion Tokens */
            completion_tokens: number;
            /** Day */
            day: string;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Turns */
            turns: number;
            /** Unpriced */
            unpriced: number;
            /** Usd */
            usd: number;
        };
        /** UsageModelOut */
        UsageModelOut: {
            /** Completion Tokens */
            completion_tokens: number;
            /** Model */
            model: string;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Turns */
            turns: number;
            /** Unpriced */
            unpriced: number;
            /** Usd */
            usd: number;
        };
        /** UsageSessionOut */
        UsageSessionOut: {
            /** Completion Tokens */
            completion_tokens: number;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Session Id */
            session_id: string;
            /** Turns */
            turns: number;
            /** Unpriced */
            unpriced: number;
            /** Usd */
            usd: number;
        };
        /** UsageSummaryOut */
        UsageSummaryOut: {
            /** By Day */
            by_day: components["schemas"]["UsageDayOut"][];
            /** By Model */
            by_model: components["schemas"]["UsageModelOut"][];
            /** By Session */
            by_session: components["schemas"]["UsageSessionOut"][];
            /** Cache Hit Pct */
            cache_hit_pct: number | null;
            /** Route Mix */
            route_mix: {
                [key: string]: number;
            };
            totals: components["schemas"]["UsageTotalsOut"];
        };
        /** UsageTotalsOut */
        UsageTotalsOut: {
            /** Cache Read Tokens */
            cache_read_tokens: number;
            /** Cache Write Tokens */
            cache_write_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Turns */
            turns: number;
            /** Unpriced Turns */
            unpriced_turns: number;
            /** Usd */
            usd: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    agents_stream_api_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agents_schema_endpoint_api_agents_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentsBatchOut"];
                };
            };
        };
    };
    benchmarks_endpoint_api_benchmarks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarksOut"];
                };
            };
        };
    };
    chat_stream_api_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_config_endpoint_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    patch_config_endpoint_api_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_test_endpoint_api_config_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigTestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cron_api_cron_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronJobOut"][];
                };
            };
        };
    };
    delete_cron_api_cron__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_cron_api_cron__job_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_cron_api_cron__job_id__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    doctor_endpoint_api_doctor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorOut"];
                };
            };
        };
    };
    fs_exec_stream_api_fs_exec_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fs_file_endpoint_api_fs_file_get: {
        parameters: {
            query: {
                path: string;
                workspace?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FsFileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fs_file_write_endpoint_api_fs_file_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FsFileWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FsFileWrittenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fs_tree_endpoint_api_fs_tree_get: {
        parameters: {
            query?: {
                path?: string;
                workspace?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FsTreeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    git_commit_endpoint_api_git_commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitCommitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitCommitOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    git_diff_endpoint_api_git_diff_get: {
        parameters: {
            query?: {
                workspace?: string | null;
                path?: string | null;
                staged?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitDiffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    git_revert_endpoint_api_git_revert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitRevertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitRevertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    git_status_endpoint_api_git_status_get: {
        parameters: {
            query?: {
                workspace?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    governance_audit_endpoint_api_governance_audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernanceAuditOut"];
                };
            };
        };
    };
    governance_injection_endpoint_api_governance_injection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjectionReportOut"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    get_kanban_api_kanban_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["TaskCardOut"][];
                    };
                };
            };
        };
    };
    maturity_endpoint_api_maturity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaturityOut"];
                };
            };
        };
    };
    mcp_list_endpoint_api_mcp_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServersOut"];
                };
            };
        };
    };
    mcp_add_endpoint_api_mcp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["McpAddRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServersOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mcp_remove_endpoint_api_mcp__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mcp_test_endpoint_api_mcp__name__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpTestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memory_api_memory_get: {
        parameters: {
            query?: {
                q?: string;
                k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_memory_api_memory_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryAddOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_layers_api_memory_layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryLayersOut"];
                };
            };
        };
    };
    memory_profile_api_memory_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryProfileOut"];
                };
            };
        };
    };
    delete_memory_api_memory__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_endpoint_api_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStateOut"][];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_project_api_projects__project_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deny_project_api_projects__project_id__deny_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_endpoint_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunReceiptOut"][];
                };
            };
        };
    };
    run_stream_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionMetaOut"][];
                };
            };
        };
    };
    new_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewSessionOut"];
                };
            };
        };
    };
    get_session_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_api_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillsOut"];
                };
            };
        };
    };
    approve_skill_api_skills__name__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_skill_api_skills__name__retire_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetiredOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tools_endpoint_api_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolsOut"];
                };
            };
        };
    };
    usage_endpoint_api_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummaryOut"];
                };
            };
        };
    };
}
