"""The values every `.env` reader must read back byte for byte, and the fixture the shell tests read.

Shared by the Python tests and, through `apps/desktop/src-tauri/fixtures/dotenv_values.tsv`, by
the desktop shell's `cargo test` (`dotenv_value.rs`, `sidecar_http.rs`). The fixture is generated
from :data:`CASES` by :func:`render`, and a test fails when the committed file differs, so the
two languages can never be checking different cases.
"""

from __future__ import annotations

from pathlib import Path

FIXTURE = (
    Path(__file__).resolve().parents[1] / "apps" / "desktop" / "src-tauri" / "fixtures"
    / "dotenv_values.tsv"
)

#: Real shapes first (API keys, model slugs, images, URLs), then every character python-dotenv
#: treats specially: quotes at the start, inside and at the end, backslashes, `#` with and without
#: a space before it, `$` without braces, `=`, spaces at the ends, non-ASCII.
CASES: list[str] = [
    "",
    "sk-or-v1-0123456789abcdef0123456789abcdef",
    "sk_live_51H$abc$$def",
    "pa$$w0rd!",
    "$NOT_A_VARIABLE",
    "${unclosed",
    "${a:b}",
    "openrouter/openai/gpt-6-luna",
    "python:3.12-slim",
    '"python:3.12-slim',
    'x"',
    'sk_"quoted"_inside',
    '"',
    "'",
    "it's",
    "'leading single",
    "trailing single'",
    "a\\b",
    "a\\'b",
    "ends with backslash\\",
    "C:\\Users\\owner\\models",
    "\\",
    "pass#word",
    "pass #word",
    "https://example.com/path#fragment",
    " leading space",
    "trailing space ",
    "key=with=equals",
    "unicodé ✓ 日本語",
    "a\\\\'b' #c",
]


def render(cases: list[str] = CASES) -> str:
    """The fixture text: a header, then ``hex(value)<TAB>encoded`` per case."""
    from chimera.api.key_vault import encode_env_value

    lines = [
        "# value as UTF-8 hex <TAB> the right-hand side chimera/api/key_vault.py writes for it.",
        "# Generated by tests/env_value_cases.py::render; tests fail if this file drifts.",
    ]
    for value in cases:
        lines.append(f"{value.encode('utf-8').hex()}\t{encode_env_value('CASE', value)}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":  # pragma: no cover - the regeneration command
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_bytes(render().encode("utf-8"))
    print(f"wrote {FIXTURE}")
