"""Generate `docs/commands.md` from the CLI snapshot.

Thirty-three of seventy-nine commands appeared in no README and no doc. Writing thirty-three entries
by hand would fix today and be wrong by the next release, because a hand-written reference goes stale
silently — the command changes, the page does not, and nothing says so.

So the page is generated from `chimera/_cli_snapshot.json`, which CI already regenerates and diffs
against the real CLI. A command cannot be added without appearing here, and an option cannot change
its name without the page changing with it. `tests/test_command_reference.py` fails if the file on
disk is not what this script produces.

Run:  python scripts/gen_command_reference.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / "chimera" / "_cli_snapshot.json"
OUT = ROOT / "docs" / "commands.md"

HEADER = """<!-- Generated by scripts/gen_command_reference.py — do not edit by hand. -->

# Every command

Generated from the CLI itself, so it cannot describe a command that does not exist or miss one that
does. Thirty-three of these appeared in no README and no doc before this page; a reference written
by hand fixes that once and then goes stale in silence, which is the failure worth designing out.

Run `chimera <command> --help` for the full text of any entry.

"""


def _signature(command: dict) -> str:
    parts = [f"chimera {command['path']}"]
    for param in command.get("params") or []:
        if param.get("kind") == "argument":
            name = str(param["name"]).upper()
            parts.append(name if param.get("required") else f"[{name}]")
    return " ".join(parts)


def _options(command: dict) -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    for param in command.get("params") or []:
        if param.get("kind") == "argument":
            continue
        flags = ", ".join(f"`{o}`" for o in param.get("opts") or [])
        default = param.get("default")
        shown = "" if default in (None, "None") else f"`{default}`"
        rows.append((flags, str(param.get("help") or ""), shown))
    return rows


def _arguments(command: dict) -> list[tuple[str, str]]:
    return [
        (f"`{str(p['name']).upper()}`", str(p.get("help") or ""))
        for p in command.get("params") or []
        if p.get("kind") == "argument"
    ]


def render(snapshot: dict) -> str:
    commands = sorted(
        (c for c in snapshot["commands"] if not c.get("hidden")),
        key=lambda c: str(c["path"]),
    )
    out = [HEADER, "| Command | What it does |", "| --- | --- |"]
    for command in commands:
        anchor = str(command["path"]).replace(" ", "-")
        summary = str(command.get("help") or "").split("\n")[0].strip()
        out.append(f"| [`{command['path']}`](#{anchor}) | {summary} |")
    out.append("")

    for command in commands:
        out.append(f"## {command['path']}")
        out.append("")
        help_text = str(command.get("help") or "").strip()
        if help_text:
            out.append(help_text)
            out.append("")
        out.append("```bash")
        out.append(_signature(command))
        out.append("```")
        out.append("")
        args = _arguments(command)
        if args:
            out.append("| Argument | |")
            out.append("| --- | --- |")
            out.extend(f"| {name} | {text} |" for name, text in args)
            out.append("")
        options = _options(command)
        if options:
            out.append("| Option | | Default |")
            out.append("| --- | --- | --- |")
            out.extend(f"| {flags} | {text} | {default} |" for flags, text, default in options)
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    text = render(json.loads(SNAPSHOT.read_text(encoding="utf-8")))
    OUT.write_text(text, encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {text.count(chr(10) + '## ')} commands")


if __name__ == "__main__":
    main()
